### ISSUE TITLE
Inconsistent Versions

### ISSUE THREAD

**Issue by robneu** [simmerwp/simmer#115]
It looks like the [version constant defined in the main plugin class](https://github.com/simmerwp/simmer/blob/development/core/class-simmer.php#L29) has been skipped the last few releases. 

This probably isn't a huge deal at the moment, but it could present problems for people who use it to test for specific features. It could also make things a little weird if and when a database upgrade needs to happen in the future.

**Comment by laralfield** [comment]
Thanks for catching this! We can go back into the prior versions in SVN on the .org directory and fix this too.

**Comment by robneu** [comment]
If it's only been a few versions, I probably wouldn't worry too much about it. No major versions have been skipped and I don't think anything super critical has been done during the missed releases. As long as it's kept in sync moving forward I think you should probably be alright.

**Comment by laralfield** [comment]
Great 👍
