### ISSUE TITLE
Turn recipe archive base permalink off by default to reduce URL redundancy? 

### ISSUE THREAD

**Issue by laralfield** [simmerwp/simmer#126]
Right now a significant majorty of support requests have to do with flexibiltiy in setting recipe permalinks. Presently, our settings for permalinks are somewhat static and unchangeable, under the "Advanced" tab for Simmer's settings page:

<img width="885" alt="screen shot 2016-01-29 at 3 02 17 pm" src="https://cloud.githubusercontent.com/assets/1518034/12686709/4f92b08a-c699-11e5-9689-3464c15cb925.png">

While the discrete distinction of each:

- Archive base
- Single recipe base
- Category base 

 works well, many find that the single recipe base default to be redundant, and wish to cut out the archive base all together. For example the current http://laralittlefield.pub/recipes/recipe/varenyky/ could be revised to http://laralittlefield.pub/recipe/varenyky/, to remove the recipe archive base. 

However, removing the recipe base could present a TON of issues potentially with post titles if they also do not have prepended slug base. While Many in SEO prefer absolutely clean URLs with no prepended base for any type of content, this just isn't realistic for a CPT in WordPress. However, if a single recipe base is always prepended, this might be enough. 

Thoughts? Better ideas? 🆒

**Comment by robneu** [comment]
:+1: to getting rid of the archive base on the single views.

I'm not sure why the multi-level URL structure was introduced in the first place, but removing the archive base from the single view would definitely be good for both SEO and just general usability of the recipes themselves.

**Comment by laralfield** [comment]
@robneu awesome! Ok, I'm really glad this makes sense. 

So that structure was very much intended to follow a system where recipe archives can be showcased really well: http://hypothyroidchef.com/recipes/ (Note that this example also uses the Simmer Private add-on you created). 

I don't want to lose the important value of the recipe archives database as a template page, which we're going to provide more documentation to our community on asap. Same thing with categories: they have a lot of value once we build more documentation and expand on template files in themes for the recipe CPT.

I think we should keep the **recipe archive base** structure exactly as is. Instead, what I'm thinking would make more sense is getting rid of the single recipe base, and just somehow have cleaner and wider options for permalinks on the settings page overall. This sort of strict adherence to structure will make implementation in a custom API for something like a mobile app later on, so in my opinion it's better to keep the structure to the degree that it best enhances the value of the recipe data. 

Also, what sort of conflict issues are we looking at if one attempts to name a recipe with the same slug as a preexisting recipe? Can we even force simple pretty permalinks on a CPT? 

@robneu: random side question: with Simmer Private, when you pull the post via JSON with an API into something like Medium, for example, does it just return back a shortcode in place or any recipe content? This would be neat to think about long term, too.

**Comment by laralfield** [comment]
This old issue can be fixed with work for #57, #61, and #59, each of which I've just added "help wanted." Thanks!
