### ISSUE TITLE
Permalink of recipe when using Simmer Private

### ISSUE THREAD

**Issue by H3llas** [simmerwp/simmer#127]
Hello all.

So when someone is using Simmer Private plugin in order to integrate recipes into the posts and not use custom post types there is a problem with itemprop="url" attribute of rich snippets meta tag.

Itemprop url in this case is http://www.domain.com/?recipe=something

Which actually is hidden and not available. 
Server also respond for that non existing URL with: SERVER RESPONSE: HTTP/1.1 200 OK

Shouldn't itemprop url then become post url where shortcode is inserted?

**Comment by H3llas** [comment]
Also from the onpage SEO side. 

If Simmer Private is active, title of the recipe should go in h2 tag not in h1 tag, since existing post title will probably be in H1 tag.

**Comment by H3llas** [comment]
I just figured Simmer Private is a third party plugin not related to Simmer. So this issue can be dissregarded.

**Comment by robneu** [comment]
If you'd like to open this issue on the [Simmer Private repo](https://github.com/wpsitecare/simmer-private), we'll work on it and collaborate with the Simmer core plugin to make any adjustments that are necessary.

**Comment by robneu** [comment]
FWIW, it looks like we're going to have to create a new template tag for getting the recipe permalink so that it can be filtered via our add-on. Right now the template uses `get_permalink` for every instance of the recipe permalink and it's hard-coded in the existing templates.

**Comment by H3llas** [comment]
I actually fixed both issue but since I am not sure how elegant this solution is. 

I modified  recipe-shortcode.php to the following:

```
 <?php
        /**
        * Detect is the Simmer Private plugin active. 
        */
        if ( function_exists('simmer_private') ) { ?>
        <h2 class="simmer-recipe-title" itemprop="name">
		<?php simmer_recipe_title(); ?>
        </h2><?php
        }
        else
        { ?>      
        <h1 class="simmer-recipe-title" itemprop="name">
		<?php simmer_recipe_title(); ?>
        </h1><?php
        }
        ?>
	<div class="simmer-recipe-meta">
		<meta itemprop="datePublished" content="<?php echo esc_attr( get_the_date( 'Y-m-d' ) ); ?>">
                <?php
                /**
                * Detect is the Simmer Private plugin active. 
                */
                if ( function_exists('simmer_private') ) {
                   $temp_post=$post;
                   wp_reset_postdata();?>
                   <meta itemprop="url" content="<?php echo get_permalink(); ?>">
                   <?php $post=$temp_post;
                } 
                else 
                { ?>
                    <meta itemprop="url" content="<?php echo get_permalink(); ?>">
                <?php 
                }
                ?>
		<p class="simmer-recipe-description" itemprop="description">

			<?php if ( simmer_recipe_has_featured_image() ) : ?>
				<?php the_post_thumbnail( 'thumbnail' ); ?>
                                <meta itemprop="image" content="<?php echo the_post_thumbnail_url('full'); ?>">
			<?php endif; ?>
			<?php $content = $post->post_content; echo esc_html( $content ); ?>
		</p>

	</div><!-- .simmer-recipe-date -->
```

Basically if Simmer Private is active than Recipe is available only via Post shortcode, so I served title of the recipe in H2.

I did the same for the URL issue. If Simmer Private is active I save the loop, reset to the first loop call article url, then restore the recipe loop. This works however it might cause certain problems for some other options probably...

I figured out that also that you can add Recipe image snippet which Google will use in search by using itemprop image for Recipe microdata format.
So as Stars Rating...

eg 
http://www.sokovi.org/kasasti-sok-od-sljiva/

However not sure how can I prevent Simmer upgrade to delete my changes?

Next problem is that Simmer Private is inserting junk spaces and tabs in the Simmer ouput...

**Comment by robneu** [comment]
The formatting issue is related to how your template code is written. Unless it's causing an actual visual problem, I think you can safely ignore it or you can rewrite the template code to avoid the extra tabs.

I think we should be able to get this fixed up in the next release of Simmer and Simmer Private, but I'll need to collaborate with @laralfield on the release. I'll work on a PR this next week and hopefully we can get things updated and released before the end of the month. :+1:

**Comment by laralfield** [comment]
@H3llas merging your code from Feb 13 for recipe-shortcode.php now.

Any files in a `/simmer` directory in your WordPress theme will not be overwritten when the Simmer plugin is updated. 

I'll post again here when I'm done testing this code and a release is ready. In the meantime, you can download an un-tested copy from `master`.

**Comment by laralfield** [comment]
01ee3c3

**Comment by laralfield** [comment]
Successfully tested, in v1.3.12. Look to the release page of this repo for the .zip soon. Working on image field next, and then will release.
