### ISSUE TITLE
Conflict when both Simmer and ACF Pro are active

### ISSUE THREAD

**Issue by dianekinney** [simmerwp/simmer#129]
I've found a very specific scenario where the Recipe embed select field drops behind the modal making it unavailable.  This only occurs when ACF Pro is active. (I'm using Pro v 5.3.4)  I've tested this on Windows Chrome and Firefox, and Mac Safari and Firefox, and it's definitely a conflict somewhere between the two plugins.  ACF is not affecting other embeds like GF or media, so I suspect something needs to happen in Simmer.

![2016-02-24_11-56-22](https://cloud.githubusercontent.com/assets/3448417/13323388/3e1009c0-dba7-11e5-9a35-08ebcc133f52.jpg)

**Comment by laralfield** [comment]
Great catch, thanks @dianekinney!

**Comment by robneu** [comment]
Looks like a z-index issue. If I had to guess, it's because ACF also uses Select2 and applies some weird styles to it or something. You may be able to namespace the simmer select box to avoid conflicts with ACF and other plugins that use Select2.

**Comment by laralfield** [comment]
@robneu 🙌 Thanks! That makes sense.
