### ISSUE TITLE
Add support for links in Instruction items

### ISSUE THREAD

**Issue by collinbarrett** [simmerwp/simmer#133]
It'd be great to allow for "a href" links in Instruction items.

**Comment by shaybocks** [comment]
I have a client looking for this as well.  :)

**Comment by laralfield** [comment]
Hi Colin and Shay! We're asked this question often :) Some time in the future Simmer's engineering team will release an add-on for both instruction and ingredient "rich" items. This will including linking, images (think GIFs, YouTubes for individual instruction items), and some other features we haven't yet released. 

Check back often at simmerwp.com/blog for updates when they're ready. Thanks for this suggestion.
