### ISSUE TITLE
New install recipe archive page & permalinks

### ISSUE THREAD

**Issue by ChaseWiseman** [simmerwp/simmer#57]
I want to set up a way for users to easily set & view their recipe archive page when Simmer is freshly installed. We already have archive page functionality in core, but I'd like to come up with a good way to show new users where the archive is and how to change it if desired.

**Comment by laralfield** [comment]
Yes! This is a great way to bring back some of the value of author pages to WordPress (which I think is an often overlooked area). 

So we want to show new users where their current archive pages are, or will be located, and I bet that the easiest way to demonstrate this is to just show an example URL of the current user what their recipe archive page will look like. It would be great to get a circle cropped gravatar just centered in the middle of the page, above or underneath a name, too. Clearly, there won't be any recipes included yet, so we'll need a default "This user hasn't published any recipes yet." We can then pair this direct copy/pastable URL on the actual page that it loads on with some information about how to use archives in the context of authorship. We'll keep all copy super, super short. Two sentence max, etc... along with a .gif or still screenshot. 

Let me know what you think :)

**Comment by ChaseWiseman** [comment]
Well, my focus here is more about archives in general. Like, somehow showing the user that all recipes live at `example.com/recipes/`, etc...

At this early stage, the main hurdle is the core architecture of how archives should work (all kinds of archives, including all recipes, category, and author), and how we want the plugin to deal with those templates moving forward. After we finalize that, we can figure out a way to inform new installs about where their recipes live.

**Comment by laralfield** [comment]
Got it. Sounds great. So let's perhaps define what kind of essential elements each template requires, and we can go from there from what (I think) I understand?

**Comment by laralfield** [comment]
This work for this issue could involve some past work to bring a welcome screen to the settings page only after a user clicks through to that page in a revamped Settings page flow ( #61  )  and also the Getting Started page for fresh install #59.

**Comment by laralfield** [comment]
Duplicate, so closing.
