### ISSUE TITLE
Recipe conversion from other recipe plugins

### ISSUE THREAD

**Issue by ChaseWiseman** [simmerwp/simmer#60]
Let's add recipe converting functionality for new installs that offers, via an admin notice, to convert data from existing recipe plugins into Simmer's format if that data is detected. Sort of like:
"Hey! It looks like you've previously used _WP Ultimate Recipe_. Would to like to update your existing recipe data to work with Simmer? [YES] [NO]"

Let's get a shortlist of 3 recipe plugins for which we'd like this notices to appear. Then we can get started on one importer/converter for each, which we'll branch off into their own unique issues.

**Comment by laralfield** [comment]
I really like the fluidity of this kind of user interface. Sounds great. 

Got it! So number one is definitely http://www.wpultimaterecipe.com/ (based on the food startups I've found and what they use for recipes most often)
Number two: https://wordpress.org/plugins/recipe-card/
Number three: https://wordpress.org/plugins/easyrecipe/

Let me know if you think any others should be added/excluded.

**Comment by laralfield** [comment]
Also possibly https://wordpress.org/plugins/zip-recipes/

**Comment by shaybocks** [comment]
Ziplist would be a great addition to this list.  Although it's no longer supported, many bloggers are still using this outdated plugin.
