### ISSUE TITLE
Jetpack & Simmer incompatability 

### ISSUE THREAD

**Issue by laralfield** [simmerwp/simmer#67]
About a week ago I tried installing the basic Jetpack plugin, and noticed that after activating, the recipes in each post still displayed themselves. However, when I connect the Jetpack plugin to an actual WordPress.com account, for some reason all recipe embeds in posts dissapear. This happens with all posts that have a recipe embed.

![screen shot 2015-07-02 at 10 03 12 am](https://cloud.githubusercontent.com/assets/1518034/8478805/8fad059c-20a1-11e5-92d5-12f47dd42a32.png)

Deactivating the plugin corrects the problem again, and the recipes appear once again in the posts.

**Comment by ChaseWiseman** [comment]
Are you seeing this issue specifically with the `[recipe]` shortcode, the single recipe post type view, or both?

**Comment by laralfield** [comment]
So we had another user report this same conflict specific to the shortcode, and hopefully he can provide us with some more details here as I've justed emailed this ticket URL to him :) 

I just retested the issue now on my own domain, and confirmed it only has to do with the shortcode, not individual recipe views (see below). So it's just related to the shortcode.

<img width="881" alt="screen shot 2015-07-08 at 3 41 58 pm" src="https://cloud.githubusercontent.com/assets/1518034/8580325/0f49efd2-2588-11e5-84fe-820b1767d409.png">

**Comment by laralfield** [comment]
Just wanted to note an obvious detail that Mariano pointed out which is the bug is "fixed" if you deactivate the Shortcode Embeds section/feature of Jetpack. So it's definitely tied to that facet. Thanks!

**Comment by laralfield** [comment]
It looks like this bug (again) is strictly limited to when the Jetpack shortcodes are activated (which is by default when a user adds Jetpack). I'm going to elevate the priority of this bug, and anyone who would like to squash it, please feel free!
