### ISSUE TITLE
Spanish translation

### ISSUE THREAD

**Issue by laralfield** [simmerwp/simmer#68]
This is an open Issue for translation of the Simmer core here into Spanish. Working parts include:
- Measurement labels
- Meta labelling, print
- Settings//all admin fields and labels
- Other UI?
- ?

**Comment by marianocaino** [comment]
I'd made all the translations to Spanish. Where I can upload the .po and .mo files?

**Comment by laralfield** [comment]
@marianocaino, fantastic!! To get started, click "Fork" at the top of this repository to create a copy to your Github account of the plugin. It's at the top right of the screen.

<img width="110" alt="screen shot 2015-07-08 at 3 55 24 pm" src="https://cloud.githubusercontent.com/assets/1518034/8580652/c5317d5a-2589-11e5-9e6a-00a8ffb5d7dc.png">

Once this repository is forked and on your account, you can go to the "Code" tab on it to view the entire file structure and code for the plugin. 

<img width="823" alt="screen shot 2015-07-08 at 3 56 43 pm" src="https://cloud.githubusercontent.com/assets/1518034/8580680/fabce450-2589-11e5-8a64-2ec2decab290.png">

Edit and upload files as needed to modify the plugin. Then, push your code to our main repository here through a merge request. I'm certain that I'm messing up or missing something with the Github open source process here, so I'll ask @ChaseWiseman to add anything I've missed.

**Comment by laralfield** [comment]
@marianocaino A great guide can be found here directly from Github: https://guides.github.com/activities/contributing-to-open-source/

**Comment by laralfield** [comment]
Version 1.3.6 adds Spanish localization with the .po and .mo files for es_ES (Spanish from Spain). We will be adding other regional Spanish versions for South America soon, too!

Thanks for your help everyone! @marianocaino
