### ISSUE TITLE
Attach an image (or a video) to an instruction step

### ISSUE THREAD

**Issue by blupu** [simmerwp/simmer#75]
It would be very nice to be able to attach an image to an instruction step. Sometimes, it helps a lot while cooking (eg. how to properly fold a brick).

**Comment by laralfield** [comment]
This is a really great feature suggestion, same as #74, but I'm just going to close it for now so it doesn't get tagged as a bug by our team. Thanks!! Please feel free to continue to add your thoughts on the feature here at anytime as a new comment.
