### ISSUE TITLE
Limit on Recent Recipes failing

### ISSUE THREAD

**Issue by topher1kenobe** [simmerwp/simmer#76]
When I add the Recent Recipes widget the limit number doesn't have any effect.

**Comment by laralfield** [comment]
@topher1kenobe Thanks for finding this! 

I've replicated this as well :+1:

**Comment by marianocaino** [comment]
If you need help to the spanish translation, just let me know.
We’re here for help.

Mariano from Buenos Aires, Argentina.

**Comment by laralfield** [comment]
@marianocaino thanks for that re: localization!! I'll talk to you soon about a small update, so I'll pull you in on a new Issue and reference the new .po base file where we'll do revisions: https://github.com/simmerwp/simmer/blob/master/languages/simmer-es_ES.po Really looking forward to continually working on localization with you.
