### ISSUE TITLE
Allow Recipes to be Embeded in Other Post Types

### ISSUE THREAD

**Issue by robneu** [simmerwp/simmer#78]
Hey guys,

Great work on this plugin so far. Pretty much all the alternatives out there are horrible so it's nice to see someone working on a sane recipe plugin. One thing I was wondering is if it's currently possible or if you plan on making it possible to embed recipes in normal posts and other post types?

The way most food bloggers I've worked with have their sites set up is as a normal blog where recipes have no real separation from the rest of their blog content other than by post categories. Semantically this is a little weird, but it's just the way they usually do things. It also allows for shorter URL structures which can be a bit better for SEO.

Migrating away from this would require changing their URLs and implementing 301 redirects which can sometimes have a negative effect on SEO, especially when you're dealing with really old posts on extremely popular sites. It's also a confusing and daunting task for your average blogger, whereas just changing over to your plugin and embedding it like they're used to doing wouldn't be that big of a deal.

I think it would help your overall adoption by food bloggers if you allowed for this type of usage. It would be even more ideal if you allowed the recipe post type to be made private so that archives and single posts don't create any duplicate content on the front end.

If you're interested, I'd be willing to work on this feature at some point either as some kind of an add-on or as part of the core plugin. What do you guys think?

**Comment by robneu** [comment]
Well, I'm an idiot. I just noticed you have this as an add-on already so I'm closing this out. Does your add-on allow for the post type to be made private? If not, it's not a huge deal to handle that in another plugin or the theme, but it would be a handy option for people who can't code.

**Comment by laralfield** [comment]
Hey @robneu, you're definitely not an idiot! There's also a recipe embed option for posts and pages right next to the "Add Media" button. 

<img width="124" alt="screen shot 2015-08-21 at 7 23 49 pm" src="https://cloud.githubusercontent.com/assets/1518034/9421013/3104ae1c-483a-11e5-8f63-4947dd8c56b2.png">

For our next major release version we want to add a welcome screen that provides an exact overview of these options when the plugin is activated. I'd love any other feedback you'd like to share at lara@simmerwp.com anytime. Thanks so much for contributing.

**Comment by robneu** [comment]
:+1: I've been playing around with the plugin a bit today and it's very, very nice. I'll definitely be recommending it to anyone with a need in the future. I was already pretty happy when all I had done was review the code but you guys have done a killer job so far. Keep up the good work!

What do you think about the suggestion of an option to make the recipe post type private? Basically turn it into more of an internal data structure than a public-facing thing for situations where the recipes are all being embedded on other posts and pages.

If you need help implementing this, I'll need it on an upcoming project anyway so I'd be happy to contribute some code. :)

**Comment by laralfield** [comment]
I'm so glad you've found Simmer for Recipes to be useful and for recommending us in the future. Thank you so much! 

Restricted/private recipes for things like memberships is definitely something we're working on in terms of new additions, but I understand you're getting at something different. Sounds like a great case for sticking 100% within the post/page URL structure. I wonder what type of conflict would arise if we set an option to set all recipes as private, but still publicly embed them in posts/pages? We'd definitely appreciate the help, so feel free to submit pull requests anytime and I'll review them immediately. Anyone is also of course, thanks to GPL, free to build paid Simmer for Recipes add-ons, too. Or ones that are entirely free :) We're working on listing 3rd party code products on our website, soon.

**Comment by robneu** [comment]
Hmm... it probably does make the most sense as an add-on. A setting could be pretty confusing, but installing a small add-on that explains why and what it does would make sense.

I'll code it up for this project and shoot over a link when it's ready for review. :)

**Comment by laralfield** [comment]
Sounds great! Looking forward to it. Feel free to ping me anytime at lara@simmerwp.com, too.

**Comment by laralfield** [comment]
Adding a note here about Simmer Private's release on our blog last year: https://simmerwp.com/blog/new-add-simmer-private/
