### ISSUE TITLE
Missing strings in .pot 

### ISSUE THREAD

**Issue by laralfield** [simmerwp/simmer#96]
Right now the final missing strings from the central .pot template file seem to be:

1. Default text in input fields on recipe edit screen 
2. Default text anywhere else in the plugin? 
3. #94 Measurment units on the back and front ends

I think that's it. Please add more here if you find any else :grinning:

**Comment by blupu** [comment]
Regarding default text in input field, when degrees are used, we should precise °F or °C.

**Comment by laralfield** [comment]
@blupu yes, great, thank you Benajmin. When we introduce precise temperature fields next, we'll make sure that the correct °C applies to all locales that use it. Thanks!
